kind: Deployment
apiVersion: apps/v1
metadata:
  name: rejector
  namespace: default
  labels:
    app: rejector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rejector
  template:
    metadata:
      labels:
        app: rejector
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: rejector
          image: tyemcq/http-rejector:v0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 1m
              memory: 2Mi
            limits:
              cpu: 8m
              memory: 8Mi

---
kind: Service
apiVersion: v1
metadata:
  name: rejector
  namespace: default
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"80":{"name":"rejector"}}}'
  labels:
    app: rejector
spec:
  type: NodePort
  selector:
    app: rejector
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
